export const FEATURES = {
    BUILT_YEAR: "featuresBuiltYear",
    AREA_CONSTRUCTED: "featuresAreaConstructed",
    AREA_PLOT: "featuresAreaPlot",
    AREA_USABLE: "featuresAreaUsable",
    BATHROOM: "featuresBathroomNumber",
    BEDROOM: "featuresBedroomNumber",
    ENERGY_CERTIFICATE: "featuresEnergyCertificaing",
    DOORMAN: "featuresDoorman",
    HEATING: "featuresHeating",
    HEATING_TYPE: "featuresHeatingType",
    CONDITIONED_AIR: "featuresConditionedAir",
    TYPE_CONDITIONED_AIR: "featuresConditionedAirType",
    ORIENTATION: {
        NORTH: "featuresOrientationNorth",
        WEST: "featuresOrientationWest",
        EAST: "featuresOrientationEast",
        SOUTH: "featuresOrientationSouth"
    },
    PARKING: "featuresParkingAvailable",
    POOL: "featuresPool",
    TERRACE: "featuresTerrace",
    GARDEN: "featuresGarden",
    WARDROBES: "featuresWardrobes",
    STORAGE: "featuresStorage",
    EQUIPPED: "featuresEquippedWithFurniture",
    EQUIPPED_KITCHEN: 'featuresEquippedKitchen',
    LIFT: "featuresLiftAvailable",
    PENT_HOUSE: "featuresPenthouse"
}
