import React from 'react'
import { StyleSheet, Text, ScrollView } from 'react-native'

styles = StyleSheet.create({
    scroller: {
        flex: 1
    }
})

export const AndroidFonts = () => (
    <ScrollView style={styles.scroller}>
        <Text style={{ fontSize: 16, fontFamily: 'normal' }}>  normal </Text>
        <Text style={{ fontSize: 16, fontFamily: 'notoserif' }}>  notoserif </Text>
        <Text style={{ fontSize: 16, fontFamily: 'sans-serif' }}>  sans-serif </Text>
        <Text style={{ fontSize: 16, fontFamily: 'sans-serif-light' }}>  sans-serif-light </Text>
        <Text style={{ fontSize: 16, fontFamily: 'sans-serif-thin' }}>  sans-serif-thin </Text>
        <Text style={{ fontSize: 16, fontFamily: 'sans-serif-condensed' }}>  sans-serif-condensed </Text>
        <Text style={{ fontSize: 16, fontFamily: 'sans-serif-medium' }}>  sans-serif-medium </Text>
        <Text style={{ fontSize: 16, fontFamily: 'serif' }}>  serif </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Roboto' }}>  Roboto </Text>
        <Text style={{ fontSize: 16, fontFamily: 'monospace' }}>  monospace </Text>
    </ScrollView>
)

export const IOSFonts = () => (
    <ScrollView style={styles.scroller}>
        <Text style={{ fontSize: 16, fontFamily: 'Academy Engraved LET' }}>Academy Engraved LET </Text>
        <Text style={{ fontSize: 16, fontFamily: 'AcademyEngravedLetPlain' }}>AcademyEngravedLetPlain </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Al Nile' }}>Al Nile </Text>
        <Text style={{ fontSize: 16, fontFamily: 'AlNile-Bold' }}>AlNile-Bold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'American Typewriter' }}>American Typewriter </Text>
        <Text style={{ fontSize: 16, fontFamily: 'AmericanTypewriter-Bold' }}>AmericanTypewriter-Bold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'AmericanTypewriter-Condensed' }}>AmericanTypewriter-Condensed </Text>
        <Text style={{ fontSize: 16, fontFamily: 'AmericanTypewriter-CondensedBold' }}>AmericanTypewriter-CondensedBold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'AmericanTypewriter-CondensedLight' }}>AmericanTypewriter-CondensedLight </Text>
        <Text style={{ fontSize: 16, fontFamily: 'AmericanTypewriter-Light' }}>AmericanTypewriter-Light </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Apple Color Emoji' }}>Apple Color Emoji </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Apple SD Gothic Neo' }}>Apple SD Gothic Neo </Text>
        <Text style={{ fontSize: 16, fontFamily: 'AppleColorEmoji' }}>AppleColorEmoji </Text>
        <Text style={{ fontSize: 16, fontFamily: 'AppleSDGothicNeo-Bold' }}>AppleSDGothicNeo-Bold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'AppleSDGothicNeo-Light' }}>AppleSDGothicNeo-Light </Text>
        <Text style={{ fontSize: 16, fontFamily: 'AppleSDGothicNeo-Medium' }}>AppleSDGothicNeo-Medium </Text>
        <Text style={{ fontSize: 16, fontFamily: 'AppleSDGothicNeo-Regular' }}>AppleSDGothicNeo-Regular </Text>
        <Text style={{ fontSize: 16, fontFamily: 'AppleSDGothicNeo-SemiBold' }}>AppleSDGothicNeo-SemiBold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'AppleSDGothicNeo-Thin' }}>AppleSDGothicNeo-Thin </Text>
        <Text style={{ fontSize: 16, fontFamily: 'AppleSDGothicNeo-UltraLight' }}>AppleSDGothicNeo-UltraLight </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Arial' }}>Arial </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Arial Hebrew' }}>Arial Hebrew </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Arial Rounded MT Bold' }}>Arial Rounded MT Bold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Arial-BoldItalicMT' }}>Arial-BoldItalicMT </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Arial-BoldMT' }}>Arial-BoldMT </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Arial-ItalicMT' }}>Arial-ItalicMT </Text>
        <Text style={{ fontSize: 16, fontFamily: 'ArialHebrew' }}>ArialHebrew </Text>
        <Text style={{ fontSize: 16, fontFamily: 'ArialHebrew-Bold' }}>ArialHebrew-Bold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'ArialHebrew-Light' }}>ArialHebrew-Light </Text>
        <Text style={{ fontSize: 16, fontFamily: 'ArialMT' }}>ArialMT </Text>
        <Text style={{ fontSize: 16, fontFamily: 'ArialRoundedMTBold' }}>ArialRoundedMTBold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Avenir' }}>Avenir </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Avenir Next' }}>Avenir Next </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Avenir Next Condensed' }}>Avenir Next Condensed </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Avenir-Black' }}>Avenir-Black </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Avenir-BlackOblique' }}>Avenir-BlackOblique </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Avenir-Book' }}>Avenir-Book </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Avenir-BookOblique' }}>Avenir-BookOblique </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Avenir-Heavy' }}>Avenir-Heavy </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Avenir-HeavyOblique' }}>Avenir-HeavyOblique </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Avenir-Light' }}>Avenir-Light </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Avenir-LightOblique' }}>Avenir-LightOblique </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Avenir-Medium' }}>Avenir-Medium </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Avenir-MediumOblique' }}>Avenir-MediumOblique </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Avenir-Oblique' }}>Avenir-Oblique </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Avenir-Roman' }}>Avenir-Roman </Text>
        <Text style={{ fontSize: 16, fontFamily: 'AvenirNext-Bold' }}>AvenirNext-Bold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'AvenirNext-BoldItalic' }}>AvenirNext-BoldItalic </Text>
        <Text style={{ fontSize: 16, fontFamily: 'AvenirNext-DemiBold' }}>AvenirNext-DemiBold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'AvenirNext-DemiBoldItalic' }}>AvenirNext-DemiBoldItalic </Text>
        <Text style={{ fontSize: 16, fontFamily: 'AvenirNext-Heavy' }}>AvenirNext-Heavy </Text>
        <Text style={{ fontSize: 16, fontFamily: 'AvenirNext-HeavyItalic' }}>AvenirNext-HeavyItalic </Text>
        <Text style={{ fontSize: 16, fontFamily: 'AvenirNext-Italic' }}>AvenirNext-Italic </Text>
        <Text style={{ fontSize: 16, fontFamily: 'AvenirNext-Medium' }}>AvenirNext-Medium </Text>
        <Text style={{ fontSize: 16, fontFamily: 'AvenirNext-MediumItalic' }}>AvenirNext-MediumItalic </Text>
        <Text style={{ fontSize: 16, fontFamily: 'AvenirNext-Regular' }}>AvenirNext-Regular </Text>
        <Text style={{ fontSize: 16, fontFamily: 'AvenirNext-UltraLight' }}>AvenirNext-UltraLight </Text>
        <Text style={{ fontSize: 16, fontFamily: 'AvenirNext-UltraLightItalic' }}>AvenirNext-UltraLightItalic </Text>
        <Text style={{ fontSize: 16, fontFamily: 'AvenirNextCondensed-Bold' }}>AvenirNextCondensed-Bold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'AvenirNextCondensed-BoldItalic' }}>AvenirNextCondensed-BoldItalic </Text>
        <Text style={{ fontSize: 16, fontFamily: 'AvenirNextCondensed-DemiBold' }}>AvenirNextCondensed-DemiBold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'AvenirNextCondensed-DemiBoldItalic' }}>AvenirNextCondensed-DemiBoldItalic </Text>
        <Text style={{ fontSize: 16, fontFamily: 'AvenirNextCondensed-Heavy' }}>AvenirNextCondensed-Heavy </Text>
        <Text style={{ fontSize: 16, fontFamily: 'AvenirNextCondensed-HeavyItalic' }}>AvenirNextCondensed-HeavyItalic </Text>
        <Text style={{ fontSize: 16, fontFamily: 'AvenirNextCondensed-Italic' }}>AvenirNextCondensed-Italic </Text>
        <Text style={{ fontSize: 16, fontFamily: 'AvenirNextCondensed-Medium' }}>AvenirNextCondensed-Medium </Text>
        <Text style={{ fontSize: 16, fontFamily: 'AvenirNextCondensed-MediumItalic' }}>AvenirNextCondensed-MediumItalic </Text>
        <Text style={{ fontSize: 16, fontFamily: 'AvenirNextCondensed-Regular' }}>AvenirNextCondensed-Regular </Text>
        <Text style={{ fontSize: 16, fontFamily: 'AvenirNextCondensed-UltraLight' }}>AvenirNextCondensed-UltraLight </Text>
        <Text style={{ fontSize: 16, fontFamily: 'AvenirNextCondensed-UltraLightItalic' }}>AvenirNextCondensed-UltraLightItalic </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Bangla Sangam MN' }}>Bangla Sangam MN </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Baskerville' }}>Baskerville </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Baskerville-Bold' }}>Baskerville-Bold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Baskerville-BoldItalic' }}>Baskerville-BoldItalic </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Baskerville-Italic' }}>Baskerville-Italic </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Baskerville-SemiBold' }}>Baskerville-SemiBold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Baskerville-SemiBoldItalic' }}>Baskerville-SemiBoldItalic </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Bodoni 72' }}>Bodoni 72 </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Bodoni 72 Oldstyle' }}>Bodoni 72 Oldstyle </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Bodoni 72 Smallcaps' }}>Bodoni 72 Smallcaps </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Bodoni Ornaments' }}>Bodoni Ornaments </Text>
        <Text style={{ fontSize: 16, fontFamily: 'BodoniOrnamentsITCTT' }}>BodoniOrnamentsITCTT </Text>
        <Text style={{ fontSize: 16, fontFamily: 'BodoniSvtyTwoITCTT-Bold' }}>BodoniSvtyTwoITCTT-Bold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'BodoniSvtyTwoITCTT-Book' }}>BodoniSvtyTwoITCTT-Book </Text>
        <Text style={{ fontSize: 16, fontFamily: 'BodoniSvtyTwoITCTT-BookIta' }}>BodoniSvtyTwoITCTT-BookIta </Text>
        <Text style={{ fontSize: 16, fontFamily: 'BodoniSvtyTwoOSITCTT-Bold' }}>BodoniSvtyTwoOSITCTT-Bold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'BodoniSvtyTwoOSITCTT-Book' }}>BodoniSvtyTwoOSITCTT-Book </Text>
        <Text style={{ fontSize: 16, fontFamily: 'BodoniSvtyTwoSCITCTT-Book' }}>BodoniSvtyTwoSCITCTT-Book </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Bradley Hand' }}>Bradley Hand </Text>
        <Text style={{ fontSize: 16, fontFamily: 'BradleyHandITCTT-Bold' }}>BradleyHandITCTT-Bold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Chalkboard SE' }}>Chalkboard SE </Text>
        <Text style={{ fontSize: 16, fontFamily: 'ChalkboardSE-Bold' }}>ChalkboardSE-Bold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'ChalkboardSE-Light' }}>ChalkboardSE-Light </Text>
        <Text style={{ fontSize: 16, fontFamily: 'ChalkboardSE-Regular' }}>ChalkboardSE-Regular </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Chalkduster' }}>Chalkduster </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Chalkduster' }}>Chalkduster </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Cochin' }}>Cochin </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Cochin-Bold' }}>Cochin-Bold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Cochin-BoldItalic' }}>Cochin-BoldItalic </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Cochin-Italic' }}>Cochin-Italic </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Copperplate' }}>Copperplate </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Copperplate-Bold' }}>Copperplate-Bold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Copperplate-Light' }}>Copperplate-Light </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Courier' }}>Courier </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Courier New' }}>Courier New </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Courier-Bold' }}>Courier-Bold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Courier-BoldOblique' }}>Courier-BoldOblique </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Courier-Oblique' }}>Courier-Oblique </Text>
        <Text style={{ fontSize: 16, fontFamily: 'CourierNewPS-BoldItalicMT' }}>CourierNewPS-BoldItalicMT </Text>
        <Text style={{ fontSize: 16, fontFamily: 'CourierNewPS-BoldMT' }}>CourierNewPS-BoldMT </Text>
        <Text style={{ fontSize: 16, fontFamily: 'CourierNewPS-ItalicMT' }}>CourierNewPS-ItalicMT </Text>
        <Text style={{ fontSize: 16, fontFamily: 'CourierNewPSMT' }}>CourierNewPSMT </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Damascus' }}>Damascus </Text>
        <Text style={{ fontSize: 16, fontFamily: 'DamascusBold' }}>DamascusBold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'DamascusLight' }}>DamascusLight </Text>
        <Text style={{ fontSize: 16, fontFamily: 'DamascusMedium' }}>DamascusMedium </Text>
        <Text style={{ fontSize: 16, fontFamily: 'DamascusSemiBold' }}>DamascusSemiBold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Devanagari Sangam MN' }}>Devanagari Sangam MN </Text>
        <Text style={{ fontSize: 16, fontFamily: 'DevanagariSangamMN' }}>DevanagariSangamMN </Text>
        <Text style={{ fontSize: 16, fontFamily: 'DevanagariSangamMN-Bold' }}>DevanagariSangamMN-Bold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Didot' }}>Didot </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Didot-Bold' }}>Didot-Bold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Didot-Italic' }}>Didot-Italic </Text>
        <Text style={{ fontSize: 16, fontFamily: 'DiwanMishafi' }}>DiwanMishafi </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Euphemia UCAS' }}>Euphemia UCAS </Text>
        <Text style={{ fontSize: 16, fontFamily: 'EuphemiaUCAS-Bold' }}>EuphemiaUCAS-Bold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'EuphemiaUCAS-Italic' }}>EuphemiaUCAS-Italic </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Farah' }}>Farah </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Futura' }}>Futura </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Futura-CondensedExtraBold' }}>Futura-CondensedExtraBold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Futura-CondensedMedium' }}>Futura-CondensedMedium </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Futura-Medium' }}>Futura-Medium </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Futura-MediumItalic' }}>Futura-MediumItalic </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Geeza Pro' }}>Geeza Pro </Text>
        <Text style={{ fontSize: 16, fontFamily: 'GeezaPro-Bold' }}>GeezaPro-Bold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Georgia' }}>Georgia </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Georgia-Bold' }}>Georgia-Bold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Georgia-BoldItalic' }}>Georgia-BoldItalic </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Georgia-Italic' }}>Georgia-Italic </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Gill Sans' }}>Gill Sans </Text>
        <Text style={{ fontSize: 16, fontFamily: 'GillSans-Bold' }}>GillSans-Bold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'GillSans-BoldItalic' }}>GillSans-BoldItalic </Text>
        <Text style={{ fontSize: 16, fontFamily: 'GillSans-Italic' }}>GillSans-Italic </Text>
        <Text style={{ fontSize: 16, fontFamily: 'GillSans-Light' }}>GillSans-Light </Text>
        <Text style={{ fontSize: 16, fontFamily: 'GillSans-LightItalic' }}>GillSans-LightItalic </Text>
        <Text style={{ fontSize: 16, fontFamily: 'GillSans-SemiBold' }}>GillSans-SemiBold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'GillSans-SemiBoldItalic' }}>GillSans-SemiBoldItalic </Text>
        <Text style={{ fontSize: 16, fontFamily: 'GillSans-UltraBold' }}>GillSans-UltraBold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Gujarati Sangam MN' }}>Gujarati Sangam MN </Text>
        <Text style={{ fontSize: 16, fontFamily: 'GujaratiSangamMN' }}>GujaratiSangamMN </Text>
        <Text style={{ fontSize: 16, fontFamily: 'GujaratiSangamMN-Bold' }}>GujaratiSangamMN-Bold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Gurmukhi MN' }}>Gurmukhi MN </Text>
        <Text style={{ fontSize: 16, fontFamily: 'GurmukhiMN-Bold' }}>GurmukhiMN-Bold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Heiti SC' }}>Heiti SC </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Heiti TC' }}>Heiti TC </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Helvetica' }}>Helvetica </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Helvetica Neue' }}>Helvetica Neue </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Helvetica-Bold' }}>Helvetica-Bold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Helvetica-BoldOblique' }}>Helvetica-BoldOblique </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Helvetica-Light' }}>Helvetica-Light </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Helvetica-LightOblique' }}>Helvetica-LightOblique </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Helvetica-Oblique' }}>Helvetica-Oblique </Text>
        <Text style={{ fontSize: 16, fontFamily: 'HelveticaNeue-Bold' }}>HelveticaNeue-Bold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'HelveticaNeue-BoldItalic' }}>HelveticaNeue-BoldItalic </Text>
        <Text style={{ fontSize: 16, fontFamily: 'HelveticaNeue-CondensedBlack' }}>HelveticaNeue-CondensedBlack </Text>
        <Text style={{ fontSize: 16, fontFamily: 'HelveticaNeue-CondensedBold' }}>HelveticaNeue-CondensedBold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'HelveticaNeue-Italic' }}>HelveticaNeue-Italic </Text>
        <Text style={{ fontSize: 16, fontFamily: 'HelveticaNeue-Light' }}>HelveticaNeue-Light </Text>
        <Text style={{ fontSize: 16, fontFamily: 'HelveticaNeue-LightItalic' }}>HelveticaNeue-LightItalic </Text>
        <Text style={{ fontSize: 16, fontFamily: 'HelveticaNeue-Medium' }}>HelveticaNeue-Medium </Text>
        <Text style={{ fontSize: 16, fontFamily: 'HelveticaNeue-MediumItalic' }}>HelveticaNeue-MediumItalic </Text>
        <Text style={{ fontSize: 16, fontFamily: 'HelveticaNeue-Thin' }}>HelveticaNeue-Thin </Text>
        <Text style={{ fontSize: 16, fontFamily: 'HelveticaNeue-ThinItalic' }}>HelveticaNeue-ThinItalic </Text>
        <Text style={{ fontSize: 16, fontFamily: 'HelveticaNeue-UltraLight' }}>HelveticaNeue-UltraLight </Text>
        <Text style={{ fontSize: 16, fontFamily: 'HelveticaNeue-UltraLightItalic' }}>HelveticaNeue-UltraLightItalic </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Hiragino Mincho ProN' }}>Hiragino Mincho ProN </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Hiragino Sans' }}>Hiragino Sans </Text>
        <Text style={{ fontSize: 16, fontFamily: 'HiraginoSans-W3' }}>HiraginoSans-W3 </Text>
        <Text style={{ fontSize: 16, fontFamily: 'HiraginoSans-W6' }}>HiraginoSans-W6 </Text>
        <Text style={{ fontSize: 16, fontFamily: 'HiraMinProN-W3' }}>HiraMinProN-W3 </Text>
        <Text style={{ fontSize: 16, fontFamily: 'HiraMinProN-W6' }}>HiraMinProN-W6 </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Hoefler Text' }}>Hoefler Text </Text>
        <Text style={{ fontSize: 16, fontFamily: 'HoeflerText-Black' }}>HoeflerText-Black </Text>
        <Text style={{ fontSize: 16, fontFamily: 'HoeflerText-BlackItalic' }}>HoeflerText-BlackItalic </Text>
        <Text style={{ fontSize: 16, fontFamily: 'HoeflerText-Italic' }}>HoeflerText-Italic </Text>
        <Text style={{ fontSize: 16, fontFamily: 'HoeflerText-Regular' }}>HoeflerText-Regular </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Iowan Old Style' }}>Iowan Old Style </Text>
        <Text style={{ fontSize: 16, fontFamily: 'IowanOldStyle-Bold' }}>IowanOldStyle-Bold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'IowanOldStyle-BoldItalic' }}>IowanOldStyle-BoldItalic </Text>
        <Text style={{ fontSize: 16, fontFamily: 'IowanOldStyle-Italic' }}>IowanOldStyle-Italic </Text>
        <Text style={{ fontSize: 16, fontFamily: 'IowanOldStyle-Roman' }}>IowanOldStyle-Roman </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Kailasa' }}>Kailasa </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Kailasa-Bold' }}>Kailasa-Bold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Kannada Sangam MN' }}>Kannada Sangam MN </Text>
        <Text style={{ fontSize: 16, fontFamily: 'KannadaSangamMN' }}>KannadaSangamMN </Text>
        <Text style={{ fontSize: 16, fontFamily: 'KannadaSangamMN-Bold' }}>KannadaSangamMN-Bold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Khmer Sangam MN' }}>Khmer Sangam MN </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Kohinoor Bangla' }}>Kohinoor Bangla </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Kohinoor Devanagari' }}>Kohinoor Devanagari </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Kohinoor Telugu' }}>Kohinoor Telugu </Text>
        <Text style={{ fontSize: 16, fontFamily: 'KohinoorBangla-Light' }}>KohinoorBangla-Light </Text>
        <Text style={{ fontSize: 16, fontFamily: 'KohinoorBangla-Regular' }}>KohinoorBangla-Regular </Text>
        <Text style={{ fontSize: 16, fontFamily: 'KohinoorBangla-Semibold' }}>KohinoorBangla-Semibold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'KohinoorDevanagari-Light' }}>KohinoorDevanagari-Light </Text>
        <Text style={{ fontSize: 16, fontFamily: 'KohinoorDevanagari-Regular' }}>KohinoorDevanagari-Regular </Text>
        <Text style={{ fontSize: 16, fontFamily: 'KohinoorDevanagari-Semibold' }}>KohinoorDevanagari-Semibold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'KohinoorTelugu-Light' }}>KohinoorTelugu-Light </Text>
        <Text style={{ fontSize: 16, fontFamily: 'KohinoorTelugu-Medium' }}>KohinoorTelugu-Medium </Text>
        <Text style={{ fontSize: 16, fontFamily: 'KohinoorTelugu-Regular' }}>KohinoorTelugu-Regular </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Lao Sangam MN' }}>Lao Sangam MN </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Malayalam Sangam MN' }}>Malayalam Sangam MN </Text>
        <Text style={{ fontSize: 16, fontFamily: 'MalayalamSangamMN' }}>MalayalamSangamMN </Text>
        <Text style={{ fontSize: 16, fontFamily: 'MalayalamSangamMN-Bold' }}>MalayalamSangamMN-Bold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Marker Felt' }}>Marker Felt </Text>
        <Text style={{ fontSize: 16, fontFamily: 'MarkerFelt-Thin' }}>MarkerFelt-Thin </Text>
        <Text style={{ fontSize: 16, fontFamily: 'MarkerFelt-Wide' }}>MarkerFelt-Wide </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Menlo' }}>Menlo </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Menlo-Bold' }}>Menlo-Bold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Menlo-BoldItalic' }}>Menlo-BoldItalic </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Menlo-Italic' }}>Menlo-Italic </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Menlo-Regular' }}>Menlo-Regular </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Mishafi' }}>Mishafi </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Noteworthy' }}>Noteworthy </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Noteworthy-Bold' }}>Noteworthy-Bold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Noteworthy-Light' }}>Noteworthy-Light </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Optima' }}>Optima </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Optima-Bold' }}>Optima-Bold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Optima-BoldItalic' }}>Optima-BoldItalic </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Optima-ExtraBlack' }}>Optima-ExtraBlack </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Optima-Italic' }}>Optima-Italic </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Optima-Regular' }}>Optima-Regular </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Oriya Sangam MN' }}>Oriya Sangam MN </Text>
        <Text style={{ fontSize: 16, fontFamily: 'OriyaSangamMN' }}>OriyaSangamMN </Text>
        <Text style={{ fontSize: 16, fontFamily: 'OriyaSangamMN-Bold' }}>OriyaSangamMN-Bold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Palatino' }}>Palatino </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Palatino-Bold' }}>Palatino-Bold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Palatino-BoldItalic' }}>Palatino-BoldItalic </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Palatino-Italic' }}>Palatino-Italic </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Palatino-Roman' }}>Palatino-Roman </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Papyrus' }}>Papyrus </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Papyrus-Condensed' }}>Papyrus-Condensed </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Party LET' }}>Party LET </Text>
        <Text style={{ fontSize: 16, fontFamily: 'PartyLetPlain' }}>PartyLetPlain </Text>
        <Text style={{ fontSize: 16, fontFamily: 'PingFang HK' }}>PingFang HK </Text>
        <Text style={{ fontSize: 16, fontFamily: 'PingFang SC' }}>PingFang SC </Text>
        <Text style={{ fontSize: 16, fontFamily: 'PingFang TC' }}>PingFang TC </Text>
        <Text style={{ fontSize: 16, fontFamily: 'PingFangHK-Light' }}>PingFangHK-Light </Text>
        <Text style={{ fontSize: 16, fontFamily: 'PingFangHK-Medium' }}>PingFangHK-Medium </Text>
        <Text style={{ fontSize: 16, fontFamily: 'PingFangHK-Regular' }}>PingFangHK-Regular </Text>
        <Text style={{ fontSize: 16, fontFamily: 'PingFangHK-Semibold' }}>PingFangHK-Semibold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'PingFangHK-Thin' }}>PingFangHK-Thin </Text>
        <Text style={{ fontSize: 16, fontFamily: 'PingFangHK-Ultralight' }}>PingFangHK-Ultralight </Text>
        <Text style={{ fontSize: 16, fontFamily: 'PingFangSC-Light' }}>PingFangSC-Light </Text>
        <Text style={{ fontSize: 16, fontFamily: 'PingFangSC-Medium' }}>PingFangSC-Medium </Text>
        <Text style={{ fontSize: 16, fontFamily: 'PingFangSC-Regular' }}>PingFangSC-Regular </Text>
        <Text style={{ fontSize: 16, fontFamily: 'PingFangSC-Semibold' }}>PingFangSC-Semibold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'PingFangSC-Thin' }}>PingFangSC-Thin </Text>
        <Text style={{ fontSize: 16, fontFamily: 'PingFangSC-Ultralight' }}>PingFangSC-Ultralight </Text>
        <Text style={{ fontSize: 16, fontFamily: 'PingFangTC-Light' }}>PingFangTC-Light </Text>
        <Text style={{ fontSize: 16, fontFamily: 'PingFangTC-Medium' }}>PingFangTC-Medium </Text>
        <Text style={{ fontSize: 16, fontFamily: 'PingFangTC-Regular' }}>PingFangTC-Regular </Text>
        <Text style={{ fontSize: 16, fontFamily: 'PingFangTC-Semibold' }}>PingFangTC-Semibold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'PingFangTC-Thin' }}>PingFangTC-Thin </Text>
        <Text style={{ fontSize: 16, fontFamily: 'PingFangTC-Ultralight' }}>PingFangTC-Ultralight </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Savoye LET' }}>Savoye LET </Text>
        <Text style={{ fontSize: 16, fontFamily: 'SavoyeLetPlain' }}>SavoyeLetPlain </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Sinhala Sangam MN' }}>Sinhala Sangam MN </Text>
        <Text style={{ fontSize: 16, fontFamily: 'SinhalaSangamMN' }}>SinhalaSangamMN </Text>
        <Text style={{ fontSize: 16, fontFamily: 'SinhalaSangamMN-Bold' }}>SinhalaSangamMN-Bold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Snell Roundhand' }}>Snell Roundhand </Text>
        <Text style={{ fontSize: 16, fontFamily: 'SnellRoundhand-Black' }}>SnellRoundhand-Black </Text>
        <Text style={{ fontSize: 16, fontFamily: 'SnellRoundhand-Bold' }}>SnellRoundhand-Bold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Symbol' }}>Symbol </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Tamil Sangam MN' }}>Tamil Sangam MN </Text>
        <Text style={{ fontSize: 16, fontFamily: 'TamilSangamMN-Bold' }}>TamilSangamMN-Bold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Telugu Sangam MN' }}>Telugu Sangam MN </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Thonburi' }}>Thonburi </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Thonburi-Bold' }}>Thonburi-Bold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Thonburi-Light' }}>Thonburi-Light </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Times New Roman' }}>Times New Roman </Text>
        <Text style={{ fontSize: 16, fontFamily: 'TimesNewRomanPS-BoldItalicMT' }}>TimesNewRomanPS-BoldItalicMT </Text>
        <Text style={{ fontSize: 16, fontFamily: 'TimesNewRomanPS-BoldMT' }}>TimesNewRomanPS-BoldMT </Text>
        <Text style={{ fontSize: 16, fontFamily: 'TimesNewRomanPS-ItalicMT' }}>TimesNewRomanPS-ItalicMT </Text>
        <Text style={{ fontSize: 16, fontFamily: 'TimesNewRomanPSMT' }}>TimesNewRomanPSMT </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Trebuchet MS' }}>Trebuchet MS </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Trebuchet-BoldItalic' }}>Trebuchet-BoldItalic </Text>
        <Text style={{ fontSize: 16, fontFamily: 'TrebuchetMS-Bold' }}>TrebuchetMS-Bold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'TrebuchetMS-Italic' }}>TrebuchetMS-Italic </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Verdana' }}>Verdana </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Verdana-Bold' }}>Verdana-Bold </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Verdana-BoldItalic' }}>Verdana-BoldItalic </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Verdana-Italic' }}>Verdana-Italic </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Zapf Dingbats' }}>Zapf Dingbats </Text>
        <Text style={{ fontSize: 16, fontFamily: 'ZapfDingbatsITC' }}>ZapfDingbatsITC </Text>
        <Text style={{ fontSize: 16, fontFamily: 'Zapfino' }}>Zapfino </Text>
    </ScrollView>
)